# Generated by Django 5.2.1 on 2025-06-07 17:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_folder_bookmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
