# Generated by Django 5.2.1 on 2025-06-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
