# Generated by Django 5.2.1 on 2025-06-08 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_bookmark_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="folder_covers",
                to="projects.projectimage",
            ),
        ),
    ]
