# Generated by Django 5.2.1 on 2025-12-25 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_productquestion"),
        ("payment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("payment", "付款相關"),
                            ("order", "訂單相關"),
                            ("refund", "退款相關"),
                            ("product", "商品相關"),
                            ("account", "帳號相關"),
                            ("other", "其他"),
                        ],
                        max_length=50,
                        verbose_name="分類",
                    ),
                ),
                ("question", models.CharField(max_length=200, verbose_name="問題")),
                ("answer", models.TextField(verbose_name="回答")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(default=True, verbose_name="啟用")),
                ("view_count", models.IntegerField(default=0, verbose_name="瀏覽次數")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "常見問題",
                "verbose_name_plural": "常見問題",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerServiceTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="主旨")),
                ("description", models.TextField(verbose_name="問題描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "開啟"),
                            ("in_progress", "處理中"),
                            ("resolved", "已解決"),
                            ("closed", "已關閉"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("urgent", "緊急"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="優先級",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解決時間"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="指派給",
                    ),
                ),
                (
                    "related_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_tickets",
                        to="database.order",
                        verbose_name="相關訂單",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "客服工單",
                "verbose_name_plural": "客服工單",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerServiceMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="訊息內容")),
                (
                    "is_from_staff",
                    models.BooleanField(default=False, verbose_name="來自客服"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="發送時間"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="發送者",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="payment.customerserviceticket",
                        verbose_name="工單",
                    ),
                ),
            ],
            options={
                "verbose_name": "客服訊息",
                "verbose_name_plural": "客服訊息",
                "ordering": ["created_at"],
            },
        ),
    ]
