# Generated by Django 5.2.1 on 2025-12-25 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdministratorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(blank=True, max_length=100, verbose_name="部門"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="電話"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "管理者資料",
                "verbose_name_plural": "管理者資料",
            },
        ),
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "建立"),
                            ("update", "更新"),
                            ("delete", "刪除"),
                            ("login", "登入"),
                            ("logout", "登出"),
                            ("payment", "支付"),
                            ("refund", "退款"),
                        ],
                        max_length=20,
                        verbose_name="操作",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="模型名稱"),
                ),
                (
                    "object_id",
                    models.CharField(blank=True, max_length=100, verbose_name="物件ID"),
                ),
                ("description", models.TextField(verbose_name="描述")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP位址"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "系統日誌",
                "verbose_name_plural": "系統日誌",
                "ordering": ["-created_at"],
            },
        ),
    ]
