# Generated by Django 5.2.1 on 2025-12-25 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="問題")),
                ("answer", models.TextField(blank=True, verbose_name="回答")),
                (
                    "answered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="回答時間"
                    ),
                ),
                ("is_public", models.BooleanField(default=True, verbose_name="公開")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提問時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "answered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answered_questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="回答者",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="database.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提問者",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品問答",
                "verbose_name_plural": "商品問答",
                "ordering": ["-created_at"],
            },
        ),
    ]
