# Generated by Django 5.2.1 on 2025-12-25 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_productquestion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="價格"
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="變動時間"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="database.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品價格歷史",
                "verbose_name_plural": "商品價格歷史",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "track_price",
                    models.BooleanField(default=True, verbose_name="追蹤價格"),
                ),
                (
                    "track_stock",
                    models.BooleanField(default=True, verbose_name="追蹤庫存"),
                ),
                (
                    "track_status",
                    models.BooleanField(default=True, verbose_name="追蹤狀態"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracked_by",
                        to="database.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracked_products",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品追蹤",
                "verbose_name_plural": "商品追蹤",
                "ordering": ["-created_at"],
                "unique_together": {("user", "product")},
            },
        ),
    ]
